name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        default: 1.8
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Version
        run: |
          VER="${{ github.event.inputs.version }}.${{ github.run_number }}" 
          echo "BUILD_NUMBER=${VER}" >> $GITHUB_ENV

      - name: Set current date as env variable
        run: echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        strategy:
          matrix:
            feature: [aws, azure, minio, rclone]
            include:
              - feature: aws
                arg: EN_AWS_CLI=true
              - feature: azure
                arg: EN_AZURE=true
              # - feature: gcloud
              #   arg: EN_GCLOUD=true
              - feature: minio
                arg: EN_MINIO=true
              - feature: rclone
                arg: EN_RCLONE=true
        with:
          labels: ${{ env.BUILD_NUMBER }}
          push: ${{ github.event_name != 'pull_request' }}-${{ matrix.version }}
          tags: |
            ${{ github.repository }}:${{ env.BUILD_NUMBER }}-${{ matrix.version }}
          build-args: |
            BUILD_DATE=${{ env.NOW }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ env.BUILD_NUMBER }}
            EN_GPG=true
            ${{ matrix.arg }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache,mode=max

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          labels: ${{ env.BUILD_NUMBER }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ github.repository }}:${{ env.BUILD_NUMBER }}-all
            ${{ github.repository }}:latest
          build-args: |
            BUILD_DATE=${{ env.NOW }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ env.BUILD_NUMBER }}
            EN_AWS_CLI=true
            EN_AZURE=true
            EN_GCLOUD=false
            EN_MINIO=true
            EN_RCLONE=true
            EN_GPG=true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache,mode=max

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BUILD_NUMBER }}
          generate_release_notes: true
